ARG DOCKER_BUILD_IMAGE

FROM ${DOCKER_BUILD_IMAGE}

ARG NPM_TOKEN
ARG NPM_REGISTRY

ENV PATH="/opt/node/bin:${PATH}"
RUN yum install -y wget

WORKDIR /opt/
RUN rm -rf src/
COPY . .
USER 1001

ENTRYPOINT ["npm", "start"]
